services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"   # jenkins web ui
      - "8081:51234"  # java app
    volumes:
      - jenkins_home:/var/jenkins_home

  ssh-agent:
    image: jenkins/ssh-agent

  # target-server:
  #   image: alpine:latest
  #   ports:
  #     - "8081:51234"

volumes:
  jenkins_home: